import { generateTriggerFile } from "../generate_trigger.ts";
import { assertSpyCall, stub } from "../dev_deps.ts";

const mkdirStub = stub(Deno, "mkdir");
const writeTextFileStub = stub(Deno, "writeTextFile");

Deno.test("generateTriggerFile creates a valid TS file", async () => {
  const input: string[] = [`--source={ "triggers": \
    [{ "type": "shortcut", \
    "name": "test trigger", \
    "description": "Testing file generation", \
    "workflow": {"callback_id": "test_trigger"}, \
     "inputs":{ \
      "interaction": {"value":"{{data.interactivity}}"}
      } 
    }]}`];

  await generateTriggerFile(input);

  // Assert directory created
  assertSpyCall(mkdirStub, 0, {
    args: ["triggers"],
  });

  // Assert file created
  assertSpyCall(writeTextFileStub, 0, {
    args: ["triggers/test_trigger.ts", validOutputOne],
  });
});

const date: string = (new Date()).toDateString();
const validOutputOne = `/** This file was autogenerated on ${date}. **/
import { Trigger } from "https://deno.land/x/deno_slack_api@1.2.0/types.ts";

/**
* Triggers determine when Workflows are executed. A trigger
* file describes a scenario in which a workflow should be run,
* such as a user pressing a button or when a specific event occurs.
* https://api.slack.com/future/triggers
*/
const testTriggerTrigger: Trigger = {
  type: "shortcut",
  name: "test trigger",
  description: "Testing file generation",
  workflow: "#/workflows/test_trigger",
  inputs: {
  interaction: {
    value: "{{data.interactivity}}",
  },
},
};

export default testTriggerTrigger;
`;
