import { parse, path } from "./deps.ts";

export type WorkflowRecord = {
  "callback_id": string;
  "function_name": string; // Name of the workflow definition function
  "file_name": string; // Name of the file the workflow definition is located in
};

export type TriggerFileRecord = {
  "type": string;
  "name": string;
  "description"?: string;
  "workflow": WorkflowRecord;
  "inputs"?: JSON;
};

export type TriggersPayload = {
  triggers: TriggerFileRecord[];
};

export interface Response {
  ok: boolean;
  files: Array<string>;
  error?: {
    message: string;
  } | null;
}

const generateTriggerFile = async (): Promise<Response> => {
  const source = parse(Deno.args).source as string;
  if (!source) throw new Error("A source path needs to be defined");

  const fullPath = path.isAbsolute(source)
    ? source
    : path.join(Deno.cwd(), source || "");

  const payload: TriggersPayload = await Deno.readTextFile(
    fullPath,
  ).then(JSON.parse);

  // Sorting alphabetically because only a monster would generate these in a random order
  payload.triggers.sort((a, b) => a.name.localeCompare(b.name));

  const directory = "triggers";
  try {
    await Deno.stat(directory);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) { // create directory
      await Deno.mkdir(directory);
    } else {
      throw error;
    }
  }

  const files: Array<string> = [];
  await Promise.all(payload.triggers.map(async (tr) => {
    console.log(
      `Generating code for Slack Workflow Trigger: ${tr.name}`,
    );
    const templateString = SlackTriggerTemplate(tr);
    const filename = directory + `/${tr.workflow.callback_id}.ts`;

    await Deno.writeTextFile(filename, templateString);
    files.push(filename);
  }));

  console.log(`Wrote ${files.length} files`);

  return { ok: true, files: files };
};

const autogeneratedComment = () => {
  const time = new Date();
  return `/** This file was autogenerated on ${time.toDateString()}. **/`;
};

export const SlackTriggerTemplate = (tr: TriggerFileRecord) => {
  const camelCase = tr.workflow.callback_id.toLowerCase().replace(
    /[^a-zA-Z0-9]+(.)/g,
    (_, chr) => chr.toUpperCase(),
  );

  return `${autogeneratedComment()}
import { Trigger } from "deno-slack-api/types.ts";
import ${tr.workflow.function_name} from "../${tr.workflow.file_name}";

/**
* Triggers determine when Workflows are executed. A trigger
* file describes a scenario in which a workflow should be run,
* such as a user pressing a button or when a specific event occurs.
* https://api.slack.com/future/triggers
*/
const ${camelCase}Trigger: Trigger<typeof ${tr.workflow.function_name}.definition> = {
  type: "${tr.type}",
  name: "${tr.name}",
  description: "${tr.description}",
  workflow: "#/workflows/${tr.workflow.callback_id}",
  inputs: {
    interactivity: {
      value: "{{data.interactivity}}",
    },
  },
};

export default ${camelCase}Trigger; 
`;
};

if (import.meta.main) {
  console.log(JSON.stringify(await generateTriggerFile()));
}
