name: Deno Continuous Deployment

on:
  push:
    paths:
      - "src/version.ts"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Extract Tag Name from version.ts
        id: save_version
        run: |
          echo "TAG_NAME=$(deno run -q --allow-read src/version.ts)" >> $GITHUB_ENV
          echo "We will now create the ${{ env.TAG_NAME }} tag."

      - name: Create and push git tag
        uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72 # v1.7.2
        with:
          tag: "${{ env.TAG_NAME }}"

      - name: Create GitHub Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          tag: "${{ env.TAG_NAME }}"
          name: "${{ env.TAG_NAME }}"
          generateReleaseNotes: true
          prerelease: true
