name: Deno Continuous Deployment

on:
  push:
    paths:
      - "src/version.ts"
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: v2.x

      - name: Extract Tag Name from version.ts
        id: save_version
        run: |
          echo "TAG_NAME=$(deno run -q --allow-read src/version.ts)" >> $GITHUB_ENV
          echo "We will now create the ${{ env.TAG_NAME }} tag."

      - name: Create and push git tag
        uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72 # v1.7.2
        with:
          tag: "${{ env.TAG_NAME }}"

      - name: Create GitHub Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          tag: "${{ env.TAG_NAME }}"
          name: "${{ env.TAG_NAME }}"
          generateReleaseNotes: true
          prerelease: true
